#!/bin/sh
#
# Copyright 2015 by Heiko Schäfer <heiko@rangun.de>
#
# This file is part of expr2cf.
#
# expr2cf is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# expr2cf is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with expr2cf.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -z "$1" ]; then
  >&2 echo "Usage: "`basename $0`" real|expression"
  exit 1
fi

CF=`echo -n "$1" | expr2cf`

if [ $? != 0 ]; then
  exit 1
else
  echo -n "$CF" | cf2expr
  if [ $? != 0 ]; then
    exit 1
  fi
fi

exit $?
